version: '3.8'

services:
  clayton-agent:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NODE_VER: 23.5.0
        PNPM_VER: 9.15.2
    container_name: clayton-agent
    volumes:
      - .:/workspace
      - node_modules:/workspace/node_modules
    ports:
      - "3000:3000"  # Server API
      - "5173:5173"  # Client
    environment:
      - NODE_ENV=development
      - ELIZA_CHARACTER=clayton
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - DIALPAD_API_KEY=${DIALPAD_API_KEY}
      - DIALPAD_API_SECRET=${DIALPAD_API_SECRET}
      - DIALPAD_ACCOUNT_ID=${DIALPAD_ACCOUNT_ID}
      - BATSCRM_API_KEY=${BATSCRM_API_KEY}
      - BATSCRM_USERNAME=${BATSCRM_USERNAME}
      - BATSCRM_PASSWORD=${BATSCRM_PASSWORD}
      - BATSCRM_BASE_URL=${BATSCRM_BASE_URL:-https://api.batscrm.com/v1}
    command: bash -c "pnpm install && pnpm build && pnpm start"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    networks:
      - clayton-network

  batscrm-simulator:
    image: node:23.5.0-alpine
    container_name: batscrm-simulator
    working_dir: /app
    volumes:
      - ./simulator/batscrm:/app
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
    command: sh -c "npm install express cors body-parser && node server.js"
    networks:
      - clayton-network

  dialpad-simulator:
    image: node:23.5.0-alpine
    container_name: dialpad-simulator
    working_dir: /app
    volumes:
      - ./simulator/dialpad:/app
    ports:
      - "9000:9000"
    environment:
      - PORT=9000
    command: sh -c "npm install express cors body-parser && node server.js"
    networks:
      - clayton-network

volumes:
  node_modules:

networks:
  clayton-network:
    driver: bridge
